- name: Demo on Loops
  hosts: all
  connection: local
  tasks:
    - name: print fruit name
      debug:
        msg: fruit name is = {{ item }}
      loop:
        - apple
        - banana
    - name: Print Fruit name & Quantity
      debug:
          msg: fruit name is {{ item.name}} and the Quantity is {{ item.quantity }}
      loop:
        - { name: "apple", quantity: 100 }
        - { name: "banana", quantity: 200}