- name: Declarative variables at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URl == {{URL}}

- name: Declarative variables at task level
  hosts: all
  connection: local
  tasks:
    - name: Declare and Access a variable at task level
      ansible.builtin.debug:
        msg: URl == {{URL}}
      vars:
        URL: task.example.com

- name: Declare a Variable from a File
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: Access a Variable From File
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: Declare a Variable from Inventory File
  hosts: all
  connection: local
  tasks:
    - name: Access a Variable
      ansible.builtin.debug:
        msg: URL == {{URL}}