- name: Declarative variables at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URl == {{URL}}

- name: Declarative variables at task level
  hosts: all
  connection: local
  tasks:
    - name: Declare and Access a variable at task level
      ansible.builtin.debug:
        msg: URl == {{URL}}
      vars:
        URL: task.example.com